# a1_layouts_geo.awk — figures/a1-four-layouts.svg 를 통째로 생성한다.
#
#   추진기 위치는 _tools/otter_config.m 과 같은 수를 쓴다:
#     y_pont = 0.395,  l_f = 1.5 (선수 팔),  l_a = 1.0 (선미 팔)
#   랭크와 열 수는 A1 C 절 러너가 찍은 값이다.
#
#   갑판 평면도: x_b(선수)를 오른쪽, y_b(우현)를 아래로 그린다.
BEGIN {
    S = 52                              # 1 m = 52 px
    yp = 0.395; lf = 1.5; la = 1.0
    W = 900; H = 534

    printf "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %d %d\" width=\"%d\" height=\"%d\"\n", W,H,W,H
    printf "     font-family=\"Segoe UI, Helvetica Neue, Arial, sans-serif\">\n"
    printf "  <rect x=\"0\" y=\"0\" width=\"%d\" height=\"%d\" fill=\"#ffffff\"/>\n", W, H
    printf "  <!-- generated by _tools/a1_layouts_geo.awk from otter_config.m geometry -->\n"
    printf "  <defs>\n"
    printf "    <marker id=\"lt\" markerWidth=\"9\" markerHeight=\"7\" refX=\"8\" refY=\"3.5\" orient=\"auto\">\n"
    printf "      <path d=\"M0,0 L9,3.5 L0,7 z\" fill=\"#1d4ed8\"/></marker>\n"
    printf "    <marker id=\"lg\" markerWidth=\"9\" markerHeight=\"7\" refX=\"8\" refY=\"3.5\" orient=\"auto\">\n"
    printf "      <path d=\"M0,0 L9,3.5 L0,7 z\" fill=\"#7c3aed\"/></marker>\n"
    printf "  </defs>\n\n"

    printf "  <text x=\"20\" y=\"30\" font-size=\"19\" font-weight=\"700\" fill=\"#1e293b\">The rank of B is decided by the picture, not by the arithmetic.</text>\n"
    printf "  <text x=\"20\" y=\"52\" font-size=\"15\" fill=\"#64748b\">Four layouts on one hull. Only the first has an empty sway row, and only the first has rank 2 &#8212; those are the same statement.</text>\n"

    panel(30,  84, "base",         "two fixed propellers",       2, 2, 0, "#dc2626")
    panel(470, 84, "aft_azimuth",  "the same two, now steerable", 3, 4, 1, "#0d9488")
    panel(30,  286,"bow_thruster", "two fixed + a bow tunnel",   3, 3, 0, "#0d9488")
    panel(470, 286,"quad_tilt",    "four steerable",             3, 8, 5, "#0d9488")

    printf "  <rect x=\"30\" y=\"472\" width=\"840\" height=\"50\" fill=\"#f8fafc\" stroke=\"#cbd5e1\" stroke-width=\"1.2\" rx=\"6\"/>\n"
    printf "  <text x=\"46\" y=\"489\" font-size=\"14\" fill=\"#334155\">A tilting thruster contributes <tspan font-weight=\"700\">two columns</tspan>, one per Cartesian component of its thrust. That is how aft_azimuth reaches rank 3 with</text>\n"
    printf "  <text x=\"46\" y=\"508\" font-size=\"14\" fill=\"#334155\">the same two physical machines as base: <tspan font-weight=\"700\">the third degree of freedom is bought with servos, not with thrusters.</tspan></text>\n"
    printf "</svg>\n"
}

function panel(px, py, nm, subt, rk, nc, nl, col,    cx, cy) {
    cx = px + 100; cy = py + 90
    printf "\n  <!-- ============ %s ============ -->\n", nm
    printf "  <text x=\"%d\" y=\"%d\" font-size=\"15\" font-weight=\"700\" fill=\"#1e293b\">%s</text>\n", px, py+14, nm
    printf "  <text x=\"%d\" y=\"%d\" font-size=\"12\" fill=\"#64748b\">%s</text>\n", px, py+31, subt

    hull(cx, cy)

    if (nm == "base") {
        fixed(cx, cy - yp*S); fixed(cx, cy + yp*S)
    } else if (nm == "aft_azimuth") {
        tilt(cx - la*S, cy - yp*S); tilt(cx - la*S, cy + yp*S)
    } else if (nm == "bow_thruster") {
        fixed(cx, cy - yp*S); fixed(cx, cy + yp*S); tunnel(cx + lf*S, cy)
    } else {
        tilt(cx + lf*S, cy - yp*S); tilt(cx + lf*S, cy + yp*S)
        tilt(cx - la*S, cy - yp*S); tilt(cx - la*S, cy + yp*S)
    }

    #  통계 — 러너가 찍은 값
    printf "  <text x=\"%d\" y=\"%d\" font-size=\"13\" fill=\"#334155\">columns <tspan font-weight=\"700\">%d</tspan>&#8194;&#8226;&#8194;rank <tspan font-weight=\"700\" fill=\"%s\">%d</tspan>&#8194;&#8226;&#8194;null <tspan font-weight=\"700\">%d</tspan></text>\n", px, py+150, nc, col, rk, nl
    if (rk == 2)
        printf "  <text x=\"%d\" y=\"%d\" font-size=\"13\" font-weight=\"700\" fill=\"#dc2626\">sway row empty &#8212; Y can never be produced</text>\n", px, py+170
    else if (nl == 0)
        printf "  <text x=\"%d\" y=\"%d\" font-size=\"13\" fill=\"#0d9488\">square: one solution, nothing to optimise</text>\n", px, py+170
    else
        printf "  <text x=\"%d\" y=\"%d\" font-size=\"13\" fill=\"#0d9488\">%d-dimensional null space: infinitely many solutions</text>\n", px, py+170, nl
}

#  선체 — 폰툰 둘. x 는 -1.1 부터 1.6 까지 (l_a, l_f 를 감싼다)
function hull(cx, cy,    x0, x1, hw) {
    x0 = cx - 1.15*S; x1 = cx + 1.65*S; hw = 0.105*S
    printf "  <rect x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" rx=\"6\" fill=\"#e2e8f0\" stroke=\"#94a3b8\" stroke-width=\"1.2\"/>\n", \
           x0, cy - yp*S - hw, x1-x0, 2*hw
    printf "  <rect x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" rx=\"6\" fill=\"#e2e8f0\" stroke=\"#94a3b8\" stroke-width=\"1.2\"/>\n", \
           x0, cy + yp*S - hw, x1-x0, 2*hw
    printf "  <rect x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" fill=\"#f1f5f9\" stroke=\"#cbd5e1\" stroke-width=\"1\" opacity=\"0.8\"/>\n", \
           x0+10, cy - yp*S, x1-x0-20, 2*yp*S
    #  선수 방향
    printf "  <text x=\"%.1f\" y=\"%.1f\" font-size=\"11\" fill=\"#94a3b8\">bow &#8594;</text>\n", x1-36, cy + yp*S + 26
}

#  고정 추진기 — 앞으로만
function fixed(x, y) {
    printf "  <rect x=\"%.1f\" y=\"%.1f\" width=\"11\" height=\"11\" fill=\"#1e293b\"/>\n", x-5.5, y-5.5
    printf "  <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" stroke=\"#1d4ed8\" stroke-width=\"2.2\" marker-end=\"url(#lt)\"/>\n", x+7, y, x+30, y
}

#  틸팅 추진기 — 두 방향, 즉 두 열
function tilt(x, y) {
    printf "  <circle cx=\"%.1f\" cy=\"%.1f\" r=\"6.5\" fill=\"#ffffff\" stroke=\"#7c3aed\" stroke-width=\"2\"/>\n", x, y
    printf "  <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" stroke=\"#7c3aed\" stroke-width=\"2\" marker-end=\"url(#lg)\"/>\n", x+8, y, x+28, y
    printf "  <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" stroke=\"#7c3aed\" stroke-width=\"2\" marker-end=\"url(#lg)\"/>\n", x, y-8, x, y-26
}

#  터널 추진기 — 옆으로만
function tunnel(x, y) {
    printf "  <rect x=\"%.1f\" y=\"%.1f\" width=\"11\" height=\"11\" fill=\"#1e293b\"/>\n", x-5.5, y-5.5
    printf "  <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" stroke=\"#1d4ed8\" stroke-width=\"2.2\" marker-end=\"url(#lt)\"/>\n", x, y+7, x, y+28
    printf "  <line x1=\"%.1f\" y1=\"%.1f\" x2=\"%.1f\" y2=\"%.1f\" stroke=\"#1d4ed8\" stroke-width=\"2.2\" marker-end=\"url(#lt)\"/>\n", x, y-7, x, y-28
}
