#!/usr/bin/env bash
#
#  w02_windup_fig.sh — figures/w02-windup.svg 를 만든다.
#
#      bash _tools/w02_windup_fig.sh
#
#  저널 그림 규약을 따른다 → _tools/bdiag.sh 머리말.
#  선 굵기 둘, 화살촉 하나, 흰 상자, 색은 강조 하나(안티와인드업 경로)뿐.
#  수식은 _tools/tex2svg.sh 가 조판하므로 본문 수식과 글자가 같다.
#
#  포화 특성의 좌표는 _tools/w02_windup_geo.awk 가 계산한 것을 그대로 쓴다.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
source _tools/bdiag.sh
OUT="figures/w02-windup.svg"
LBL="_tools/labels/w02-windup.txt"

Y=170                      # 신호선 높이
{
cat <<'HDR'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 470" width="900" height="470"
     font-family="Segoe UI, Helvetica Neue, Arial, sans-serif">
  <rect x="0" y="0" width="900" height="470" fill="#ffffff"/>
  <!-- generated by _tools/w02_windup_fig.sh ; style _tools/bdiag.sh ; math _tools/tex2svg.sh -->
HDR
bd_defs

cat <<'CAP'
  <text x="20" y="28" font-size="18" font-weight="700" fill="#1a1a1a">Windup is not a fault of the integrator. It is what an integrator does to an open loop.</text>
  <text x="20" y="49" font-size="14" fill="#555">While the actuator sits on its limit the feedback path is cut, and the integrator keeps integrating an error it can no longer affect</text>
  <text x="40" y="86" font-size="13" font-weight="700" fill="#1a1a1a">(a)&#8194;where the loop breaks</text>
  <text x="512" y="86" font-size="13" font-weight="700" fill="#1a1a1a">(b)&#8194;how far outside the limit the demand went</text>
CAP

# ---------------------------------------------------------------- (a) the loop
bd_sig 40 $Y 79 $Y
bd_sum 88 $Y
bd_sign 78 $((Y-12)) "+"
bd_sign 74 $((Y+20)) "&#8722;"

bd_wire 97 $Y 108 $Y
bd_dot  108 $Y
bd_wire 108 $((Y-21)) 108 $((Y+21))
bd_sig  108 $((Y-21)) 122 $((Y-21))
bd_sig  108 $((Y+21)) 122 $((Y+21))
bd_blk 122 $((Y-36)) 64 30
bd_blk 122 $((Y+6))  64 30
bd_wire 186 $((Y-21)) 206 $((Y-21))
bd_wire 186 $((Y+21)) 206 $((Y+21))
bd_wire 206 $((Y-21)) 206 $((Y+21))
bd_sig  206 $Y 215 $Y
bd_sum 224 $Y
bd_sign 214 $((Y-12)) "+"
bd_sign 236 $((Y-12)) "+"

bd_sig 233 $Y 276 $Y
bd_blk 276 $((Y-18)) 68 36
#  포화 특성 글리프. 상자 안에 글자를 또 넣지 않는다 — 저널 관행이다
printf '  <polyline points="286,%s 298,%s 322,%s 334,%s" fill="none" stroke="%s" stroke-width="1.5"/>\n' \
       $((Y+10)) $((Y+10)) $((Y-10)) $((Y-10)) "$BD_INK"
bd_sig 344 $Y 400 $Y
bd_blk 400 $((Y-18)) 62 36
bd_wire 462 $Y 486 $Y
bd_dot  486 $Y
bd_sig  486 $Y 510 $Y

#  되먹임
bd_wire 486 $Y 486 $((Y+98))
bd_wire 486 $((Y+98)) 88 $((Y+98))
bd_sig  88 $((Y+98)) 88 $((Y+11))

#  루프가 끊기는 자리 — 작고 가늘게. 크게 그리면 그림이 포스터가 된다
printf '  <g stroke="#b91c1c" stroke-width="1.8">\n'
printf '    <line x1="366" y1="%s" x2="378" y2="%s"/>\n' $((Y-8)) $((Y+8))
printf '    <line x1="378" y1="%s" x2="366" y2="%s"/>\n' $((Y-8)) $((Y+8))
printf '  </g>\n'
bd_note 372 $((Y+24)) 11 middle "cut"

#  안티와인드업 — 진짜 구조대로: X_cmd 와 X_sat 의 차를 만들어 적분기로 되돌린다
bd_dot 256 $Y
bd_wire 256 $Y 256 $((Y+56))
bd_sigA 256 $((Y+56)) 306 $((Y+56))
bd_dot 356 $Y
bd_wire 356 $Y 356 $((Y+56))
bd_sigA 356 $((Y+56)) 324 $((Y+56))
printf '  <circle cx="315" cy="%s" r="9" fill="#ffffff" stroke="%s" stroke-width="%s"/>\n' \
       $((Y+56)) "$BD_ACC" "$BD_BOX"
printf '  <text x="301" y="%s" font-size="11" fill="%s" text-anchor="middle">+</text>\n' $((Y+44)) "$BD_ACC"
printf '  <text x="331" y="%s" font-size="11" fill="%s" text-anchor="middle">&#8722;</text>\n' $((Y+44)) "$BD_ACC"
bd_wireA 315 $((Y+65)) 315 $((Y+82))
bd_wireA 315 $((Y+82)) 154 $((Y+82))
bd_sigA  154 $((Y+82)) 154 $((Y+42))

# ---------------------------------------------------------------- (b) the sat curve
cat <<'PLOT'
  <line x1="545" y1="330" x2="870" y2="330" stroke="#1a1a1a" stroke-width="1"/>
  <line x1="583.7" y1="130" x2="583.7" y2="330" stroke="#1a1a1a" stroke-width="1"/>
  <polyline points="545,297.9 573.4,297.9 602.2,159.9 870,159.9"
            fill="none" stroke="#1a1a1a" stroke-width="1.8"/>
  <line x1="583.7" y1="159.9" x2="870" y2="159.9" stroke="#888" stroke-width="0.9" stroke-dasharray="4 3"/>
  <line x1="853" y1="330" x2="853" y2="159.9" stroke="#7c3aed" stroke-width="1.4" stroke-dasharray="5 3"/>
  <circle cx="853" cy="159.9" r="3.6" fill="#7c3aed"/>
  <text x="583.7" y="346" font-size="11" fill="#555" text-anchor="middle">0</text>
  <text x="699.8" y="346" font-size="11" fill="#555" text-anchor="middle">1500</text>
  <text x="815.8" y="346" font-size="11" fill="#555" text-anchor="middle">3000</text>
PLOT

# ---------------------------------------------------------------- captions
cat <<'FTR'
  <line x1="40" y1="386" x2="860" y2="386" stroke="#cbd5e1" stroke-width="1"/>
  <text x="40" y="406" font-size="13" fill="#333">(a)  On the limit the actuator output stops following its input, so nothing the controller does reaches the hull and the error cannot change sign.</text>
  <text x="40" y="424" font-size="13" fill="#333">The violet path is the only addition either anti-windup scheme makes. It carries the difference between demand and delivery, which is</text>
  <text x="40" y="442" font-size="13" fill="#333">identically zero while the actuator follows &#8212; so an unsaturated loop cannot tell whether anti-windup is fitted.</text>
  <text x="40" y="462" font-size="13" fill="#333">(b)  The characteristic drawn to scale. Section F measured a peak demand of 3480 N against a limit of 239.36 N: an overdraft of 14.5 times.</text>
</svg>
FTR
} > "$OUT"

#  수식 라벨을 그림 안으로. </svg> 앞에 끼워 넣는다
FR="$(bash _tools/tex2svg.sh -p "$LBL")"
grep -v '</svg>' "$OUT" > "$OUT.tmp"
printf '%s\n</svg>\n' "$FR" >> "$OUT.tmp"
mv "$OUT.tmp" "$OUT"

echo "  wrote $OUT"
bash _tools/svg2png.sh "$OUT"
