#!/usr/bin/env bash
#
#  w04_three_laws.sh — figures/w04-three-laws.svg 를 만든다.
#
#      bash _tools/w04_three_laws.sh
#
#  세 유도법칙의 **구조적 차이**를 한 장에 세운다. 물리적 결과(뱃머리가 상류로
#  기운다)는 w04-ilos-alos-idea.svg 가 보이고, 이 그림은 그 앞 단계 —
#  "식의 어디가 다른가" — 를 본다. 차이는 한 문장으로 끝난다:
#
#      ILOS 는 arctan **안**에 항을 더하고, ALOS 는 arctan **밖**에 더한다.
#
#  수식은 _tools/tex2svg.sh 로 조판한다. 본문 PDF 와 같은 MathJax 번들이므로
#  글꼴과 자간이 본문 수식과 정확히 같다.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
T="_tools/tex2svg.sh"
OUT="figures/w04-three-laws.svg"

#  한 줄 = 수식 하나. tex2svg 가 <g> 로 돌려준다.
tex() { bash "$T" "$@" | grep '^<g'; }

ROW1=120; ROW2=270; ROW3=420        # 각 행의 위쪽
EQY=64                              # 행 위쪽에서 수식 기준선까지

{
cat <<'HDR'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 630" width="900" height="630"
     font-family="Segoe UI, Helvetica Neue, Arial, sans-serif">
  <rect x="0" y="0" width="900" height="630" fill="#ffffff"/>
  <!-- generated by _tools/w04_three_laws.sh ; equations typeset by _tools/tex2svg.sh -->
  <defs>
    <marker id="k" markerWidth="9" markerHeight="7" refX="8" refY="3.5" orient="auto">
      <path d="M0,0 L9,3.5 L0,7 z" fill="#334155"/></marker>
    <marker id="v" markerWidth="9" markerHeight="7" refX="8" refY="3.5" orient="auto">
      <path d="M0,0 L9,3.5 L0,7 z" fill="#7c3aed"/></marker>
  </defs>

  <text x="20" y="30" font-size="19" font-weight="700" fill="#1e293b">The three laws differ in one place only: where the extra term is added.</text>
  <text x="20" y="52" font-size="15" fill="#64748b">ILOS puts it INSIDE the arctan, so it looks like more cross-track error. ALOS puts it OUTSIDE, so it looks like a rotated path.</text>

  <line x1="30" y1="72" x2="870" y2="72" stroke="#cbd5e1" stroke-width="1"/>
  <text x="30"  y="92" font-size="13" font-weight="700" fill="#64748b">THE LAW</text>
  <text x="470" y="92" font-size="13" font-weight="700" fill="#64748b">WHERE THE TERM ENTERS</text>
  <text x="720" y="92" font-size="13" font-weight="700" fill="#64748b">WHAT THE STATE IS</text>
  <line x1="30" y1="102" x2="870" y2="102" stroke="#cbd5e1" stroke-width="1"/>
HDR

# ---------------------------------------------------------------- row helper
# $1 row-top  $2 name  $3 colour  $4 flag: none|inside|outside
row() {
  local Y=$1 NAME=$2 COL=$3 KIND=$4
  local bx=470 by=$((Y+34))          # mini diagram origin
  echo "  <text x=\"30\" y=\"$((Y+16))\" font-size=\"16\" font-weight=\"700\" fill=\"$COL\">$NAME</text>"

  # ---- mini block diagram: y_e -> [arctan] -> (sum) -> psi_d, pi_p from above
  echo "  <line x1=\"$((bx+26))\" y1=\"$((by+42))\" x2=\"$((bx+54))\" y2=\"$((by+42))\" stroke=\"#334155\" stroke-width=\"1.6\" marker-end=\"url(#k)\"/>"
  echo "  <rect x=\"$((bx+58))\" y=\"$((by+26))\" width=\"74\" height=\"32\" rx=\"4\" fill=\"#eff6ff\" stroke=\"#1d4ed8\" stroke-width=\"1.5\"/>"
  echo "  <text x=\"$((bx+95))\" y=\"$((by+47))\" font-size=\"13\" fill=\"#1e293b\" text-anchor=\"middle\">arctan</text>"
  echo "  <line x1=\"$((bx+132))\" y1=\"$((by+42))\" x2=\"$((bx+160))\" y2=\"$((by+42))\" stroke=\"#334155\" stroke-width=\"1.6\" marker-end=\"url(#k)\"/>"
  echo "  <circle cx=\"$((bx+174))\" cy=\"$((by+42))\" r=\"11\" fill=\"#ffffff\" stroke=\"#334155\" stroke-width=\"1.6\"/>"
  echo "  <text x=\"$((bx+174))\" y=\"$((by+47))\" font-size=\"13\" fill=\"#334155\" text-anchor=\"middle\">&#8722;</text>"
  echo "  <line x1=\"$((bx+174))\" y1=\"$((by+8))\" x2=\"$((bx+174))\" y2=\"$((by+29))\" stroke=\"#334155\" stroke-width=\"1.6\" marker-end=\"url(#k)\"/>"
  echo "  <line x1=\"$((bx+185))\" y1=\"$((by+42))\" x2=\"$((bx+212))\" y2=\"$((by+42))\" stroke=\"#334155\" stroke-width=\"1.6\" marker-end=\"url(#k)\"/>"
  tex -s 14 -x $((bx))     -y $((by+47)) 'y_e'
  tex -s 14 -x $((bx+180)) -y $((by+6))  '\pi_p'
  tex -s 14 -x $((bx+218)) -y $((by+47)) '\psi_d'

  case "$KIND" in
    inside)
      echo "  <line x1=\"$((bx+95))\" y1=\"$((by+80))\" x2=\"$((bx+95))\" y2=\"$((by+62))\" stroke=\"#7c3aed\" stroke-width=\"2.2\" marker-end=\"url(#v)\"/>"
      tex -s 14 -a middle -x $((bx+95)) -y $((by+96)) '\kappa\,y_{int}'
      echo "  <text x=\"$((bx+95))\" y=\"$((by+22))\" font-size=\"12\" font-weight=\"700\" fill=\"#7c3aed\" text-anchor=\"middle\">INSIDE</text>"
      ;;
    outside)
      echo "  <line x1=\"$((bx+174))\" y1=\"$((by+80))\" x2=\"$((bx+174))\" y2=\"$((by+56))\" stroke=\"#7c3aed\" stroke-width=\"2.2\" marker-end=\"url(#v)\"/>"
      tex -s 14 -a middle -x $((bx+174)) -y $((by+96)) '\hat\beta'
      echo "  <text x=\"$((bx+186))\" y=\"$((by+72))\" font-size=\"12\" font-weight=\"700\" fill=\"#7c3aed\">OUTSIDE</text>"
      ;;
    *)
      echo "  <text x=\"$((bx+95))\" y=\"$((by+96))\" font-size=\"12\" fill=\"#94a3b8\" text-anchor=\"middle\">nothing else enters</text>"
      ;;
  esac
}

# ---------------------------------------------------------------- the rows
row $ROW1 "1  LOS"  "#dc2626" none
tex -d -s 19 -x 30 -y $((ROW1+EQY)) '\psi_d = \pi_p - \arctan\!\left(\dfrac{y_e}{\Delta}\right)'
cat <<EOF
  <text x="720" y="$((ROW1+30))" font-size="13" fill="#334155">no state at all</text>
  <text x="720" y="$((ROW1+50))" font-size="13" fill="#334155">settles at <tspan font-weight="700" fill="#dc2626">2.253 m</tspan> off</text>
  <text x="720" y="$((ROW1+68))" font-size="13" fill="#334155">the path in a 0.3 m/s</text>
  <text x="720" y="$((ROW1+86))" font-size="13" fill="#334155">beam current</text>
  <line x1="30" y1="$((ROW1+142))" x2="870" y2="$((ROW1+142))" stroke="#e2e8f0" stroke-width="1"/>
EOF

row $ROW2 "2  ILOS" "#0d9488" inside
tex -s 14 -x 720 -y $((ROW2+30)) 'y_{int}'
tex -d -s 19 -x 30 -y $((ROW2+EQY)) '\psi_d = \pi_p - \arctan\!\left(\dfrac{y_e + \color{#7c3aed}{\kappa\,y_{int}}}{\Delta}\right)'
cat <<EOF
  <text x="745" y="$((ROW2+30))" font-size="13" fill="#334155">, in seconds</text>
  <text x="720" y="$((ROW2+50))" font-size="13" fill="#334155">ends at <tspan font-weight="700">7.516</tspan> &#8212; a number</text>
  <text x="720" y="$((ROW2+68))" font-size="13" fill="#334155">with no physical meaning</text>
  <text x="720" y="$((ROW2+90))" font-size="13" fill="#334155">settles at <tspan font-weight="700" fill="#0d9488">0.008 m</tspan></text>
  <line x1="30" y1="$((ROW2+142))" x2="870" y2="$((ROW2+142))" stroke="#e2e8f0" stroke-width="1"/>
EOF

row $ROW3 "3  ALOS" "#7c3aed" outside
tex -s 14 -x 720 -y $((ROW3+30)) '\hat\beta'
tex -d -s 19 -x 30 -y $((ROW3+EQY)) '\psi_d = \pi_p - \color{#7c3aed}{\hat\beta} - \arctan\!\left(\dfrac{y_e}{\Delta}\right)'
cat <<EOF
  <text x="733" y="$((ROW3+30))" font-size="13" fill="#334155">, in degrees</text>
  <text x="720" y="$((ROW3+50))" font-size="13" fill="#334155">ends at <tspan font-weight="700">15.91&#176;</tspan> against a</text>
  <text x="720" y="$((ROW3+68))" font-size="13" fill="#334155">true crab angle of 15.88&#176;</text>
  <text x="720" y="$((ROW3+90))" font-size="13" fill="#334155">settles at <tspan font-weight="700" fill="#7c3aed">&#8722;0.004 m</tspan></text>
EOF

cat <<'FTR'
  <rect x="30" y="566" width="840" height="50" fill="#f5f3ff" stroke="#7c3aed" stroke-width="1.2" rx="6"/>
  <text x="46" y="588" font-size="14" fill="#334155">Inside the arctan, a term is <tspan font-weight="700">indistinguishable from more cross-track error</tspan> &#8212; ILOS steers as if the vessel were 2.25 m further out.</text>
  <text x="46" y="607" font-size="14" fill="#334155">Outside it, a term is <tspan font-weight="700">indistinguishable from a rotated path</tspan> &#8212; ALOS steers along a line tilted by the drift it estimated.</text>
</svg>
FTR
} > "$OUT"

echo "  wrote $OUT"
bash _tools/svg2png.sh "$OUT"
