%% W01_0_setup — 이번 주에 학생이 고치는 유일한 파일
%  W01_0_setup — the only file to be edited in Week 1
%
%  강의에서의 위치 / place in the lecture
%      Part 2 의 절 A 에 해당한다. 이후의 모든 절이 여기서 만든 변수를 그대로
%      쓰므로, 실습을 시작할 때 가장 먼저 실행한다.
%
%      This is section A of Part 2. Every later section uses the variables it
%      defines, so it is the first thing to run in the laboratory.
%
%  이 파일의 역할 / what this file is for
%      W01_openloop.slx 의 모든 Constant 블록은 값을 직접 갖고 있지 않고 여기서
%      정의한 변수의 이름을 갖고 있다. 따라서 값을 바꾸려면 모델을 열 필요 없이
%      이 파일의 숫자를 고치고 다시 실행하면 된다. 실험 조건이 한곳에 모여 있어야
%      무엇을 바꾸어 무엇이 달라졌는지 말할 수 있다.
%
%      The Constant blocks of W01_openloop.slx hold variable names rather than
%      numbers, and those variables are defined here. A value is therefore
%      changed by editing this file and running it again, without opening the
%      model. Keeping the conditions of an experiment in one place is what
%      makes it possible to say which change produced which result.
%
%  실행 / to run
%      W01_0_setup
%
%  그다음 절을 하나씩 / then, one laboratory section at a time
%      W01_C_terminal_speed    절 C — 종이로 예측한 종단속도를 측정과 비교한다
%                              section C — the terminal speed, predicted then measured
%      W01_D_the_manoeuvre     절 D — 직진·좌선회·직진·우선회의 S 자 기동
%                              section D — straight, port, straight, starboard
%      W01_E_current_run       절 E — 같은 명령을 네 가지 조류에서 반복한다
%                              section E — one command, four ocean currents
%
%  모델이 망가졌을 때 / to rebuild a model that has been damaged
%      W01_1_build_openloop        W01_openloop.slx 를 코드에서 다시 만든다
%      W01_E_build_current         W01_current.slx 를 코드에서 다시 만든다
%      모델은 손으로 그린 것이 아니라 스크립트가 만든 것이므로, 마음껏 고쳐 보고
%      망가지면 위의 한 줄로 되돌리면 된다.
%      The models are generated by script rather than drawn by hand, so they
%      may be modified freely and restored with a single command.

clear; close all; bdclose('all');

here = fileparts(mfilename('fullpath'));
root = fileparts(fileparts(here));            % ...\GradCourse
addpath(fullfile(root,'_tools'), here);
mss_path();                                   % locates MSS wherever it lives

%% ---- the manoeuvre ------------------------------------------------------
%  straight  ->  turn to port  ->  straight  ->  turn to starboard  ->  straight
%
%  Both propellers run ahead the whole time. A turn is a small DIFFERENCE
%  between them:
%
%     straight       n = [n0    ; n0   ]
%     to port        n = [n0-dn ; n0+dn]
%     to starboard   n = [n0+dn ; n0-dn]
%
%  because the yaw moment is N = y_p (T_left - T_right). More thrust on the
%  left turns the bow to starboard, so a PORT turn slows the LEFT propeller.

n0 = 60;          % common shaft speed [rad/s] — sets the speed, about 1.03 m/s
dn = 3.5;         % differential [rad/s] — sets the turn rate, about 3.2 deg/s

%  phase boundaries [s]:  port turn runs t_phase(1)..t_phase(2)
%                         starboard turn runs t_phase(3)..t_phase(4)
t_phase = [30 60 90 120];

%  dn = 0 collapses the manoeuvre to a constant command. W01_C_terminal_speed uses that for
%  the terminal-speed sweep, where a turn would only get in the way.

%% ---- vessel and environment --------------------------------------------
mp     = 25;                  % payload mass [kg], otter.m accepts up to 45
rp     = [0.05 0 -0.35]';     % payload position in {b} [m]
V_c    = 0;                   % current speed [m/s]
beta_c = 0;                   % current direction [rad]

%% ---- initial state ------------------------------------------------------
%  x = [u v w p q r  x y z  phi theta psi]'
x0        = zeros(12,1);
x0(12)    = 0;                % initial heading [rad]

%% ---- simulation ---------------------------------------------------------
h       = 0.02;               % fixed step [s]
T_final = 150;                % the whole manoeuvre, with a straight leg after it

%% ---- live view -----------------------------------------------------------
%  The model draws the hull, its heading and its track while the simulation
%  runs. Watching the heading line matters here: in each turn the vessel
%  points one way and moves another, and no track on its own shows that.
animate       = 1;            % 1 draws the live view, 0 switches it off
animate_every = 0.5;          % redraw interval in simulated seconds

%  The axes are fixed before the run starts, so they do not auto-range.
%  Widen these if the vessel leaves the box. The S-shape runs about 130 m
%  north and swings about 65 m to the west before straightening up again.
track_Nmin = -10;   track_Nmax = 140;
track_Emin = -85;   track_Emax =  25;

%% ---- report -------------------------------------------------------------
cfg = otter_config('base');
fprintf('\n  W01 setup complete\n');
fprintf('    configuration   %s, %d thrusters, rank(B) = %d\n', ...
        cfg.name, cfg.n_thr, rank(cfg.B));
fprintf('    manoeuvre       n0 = %g, dn = %g rad/s\n', n0, dn);
fprintf('                    port %g..%g s, starboard %g..%g s\n', t_phase);
fprintf('    n limits        %.1f .. %.1f rad/s\n', cfg.n_min, cfg.n_max);
fprintf('    current         %.2f m/s at %.0f deg\n', V_c, rad2deg(beta_c));
fprintf('    simulation      %g s at h = %g s\n\n', T_final, h);
